YetAnotherTestProject/WebClient/Controllers/VacancyController.cs
using System;
using System.Web.Mvc;
using BusinessLayer.Abstract;
using BusinessLayer.Contracts;
using DataAccess.Abstract;
using Model.Entities;

namespace WebClient.Controllers {
    public class VacancyController : Controller {
        private readonly IVacancyManager _vacancyManager;

        public VacancyController(IVacancyManager vacancyManager) {
            _vacancyManager = vacancyManager;
        }


        [HttpGet]
        public ActionResult Index(string siteUrl, bool getFromDb = true) {
            return View(_vacancyManager.GetVacancies(new GetVacanciesRequest() {
                GetFromDb = getFromDb,
                SiteUrl = siteUrl
            }));
        }
    }
}

YetAnotherTestProject/WebClient/Views/Shared/_Grid.cshtml
@using System.Activities
@using System.Activities.Statements
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
            <tr class="grid-row @Model.GetRowCssClasses(item)">
                @foreach (IGridColumn column in Model.Columns) {
                    @column.CellRenderer.Render(column, column.GetCell(item))
                }
            </tr>
            <tr class="grid-row under-row">
                @foreach (IGridColumn column in Model.Columns) {
                    if (column.Name == "Description") {
                        var vacancy = (dynamic) item;

                        <td colspan="@Model.Columns.Count()">
                            <table class="table table-striped grid-table">
                                <thead>
                                    <tr>
                                        <th class="grid-header">Описание</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="grid-cell">@vacancy.Description</td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    }
                }
            </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

YetAnotherTestProject/WebClient/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

YetAnotherTestProject/WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/gridmvc.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Вакансии", "Index", "Vacancy", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>*@
</body>
</html>

YetAnotherTestProject/WebClient/Views/Vacancy/Index.cshtml
@using GridMvc.Html
@using Model.Entities

@{
    ViewBag.Title = "View";
}


@model BusinessLayer.Contracts.GetVacanciesResponse

<h2>Вакансии</h2>

<div class="panel panel-default">
    <form action="/Vacancy/Index" method="get">  
        <div class="panel-heading"></div>
        <div class="panel-body">
            <div class="form-group" name="siteUrlContainer" id="siteUrlContainer">
                <label for="siteUrl">Ссылка на вакансии</label>
                <input type="url" class="form-control" id="siteUrl" name="siteUrl">
            </div>
            <div class="checkbox">
                <label>
                    @Html.CheckBox("getFromDb")
                    Из базы данных
                </label>
            </div>
            <button type="submit" class="btn btn-primary">Получить данные</button>
        </div>
    </form>
</div>

@if (Model.IsError) {
    <p class="alert alert-danger">@Model.ErrorMessage</p>
}
else
{
    <p class="alert alert-success">@Model.ErrorMessage</p>
}


@(Html
    .Grid(Model.Vacancies).Named("vacancies")
    .Columns(columns =>
    {
        columns.Add(vacancy => vacancy.Id, true).Titled("Id").Sortable(true).Filterable(true);
        columns.Add(vacancy => vacancy.Title).Titled("Должность").Sortable(true).Filterable(true);
        columns.Add(vacancy => vacancy.Salary).Titled("Оклад").Sortable(true).Filterable(true);
        columns.Add(vacancy => vacancy.Company.Name).Titled("Компания").Sortable(true).Filterable(true);
        columns.Add(vacancy => vacancy.EmploymentType).Titled("Тип занятости").Sortable(true).Filterable(true);
        columns.Add(vacancy => vacancy.Description, true).Titled("Under-Row");
    }).SetRowCssClasses(vacancy=>vacancy.Id.ToString()).Sortable().Filterable().WithPaging(20)
      )

<script>
    $(function() {
        pageGrids.vacancies.onRowSelect(e => {
            $("." + e.row['Id'] + " + .under-row").toggle();
            //console.log(e.row);
        });
    });

    $("#getFromDb").change(function () {
        $("#siteUrlContainer").toggle();
    });
</script>